import type { CSSProperties } from "react";

// Background fields (canvasBgColor, bgColor) are free-form strings that hold
// either a plain hex color or a generated `linear-gradient(...)` string --
// no schema change needed since `background-image` accepts both shapes of
// value once routed to the right CSS property.
const GRADIENT_PREFIX = "linear-gradient(";

export function isGradient(value: string): boolean {
  return value.startsWith(GRADIENT_PREFIX);
}

export function resolveBackgroundStyle(
  value: string | null | undefined,
  fallback: string,
): Pick<CSSProperties, "backgroundColor" | "backgroundImage"> {
  const v = value ?? fallback;
  return isGradient(v) ? { backgroundImage: v } : { backgroundColor: v };
}

export function buildGradient(angle: number, colors: string[]): string {
  return `${GRADIENT_PREFIX}${angle}deg, ${colors.join(", ")})`;
}

/** Parses a string generated by buildGradient. Returns null for a plain color or unset value. */
export function parseGradient(value: string | null | undefined): { angle: number; colors: string[] } | null {
  if (!value || !isGradient(value)) return null;
  const inner = value.slice(GRADIENT_PREFIX.length, -1);
  const [anglePart, ...colorParts] = inner.split(",").map((s) => s.trim());
  const angle = parseInt(anglePart, 10);
  if (Number.isNaN(angle) || colorParts.length < 2) return null;
  return { angle, colors: colorParts };
}
